working directory:  /home/megu/ECoG_CNNs
omp thread num:  1
ncpus:  1
cuda visible devices:  GPU-7bbdfddb-899d-ec05-00f1-27e63c9f71b9
Traceback (most recent call last):
  File "learning.py", line 140, in <module>
    
  File "/new_nas/megu/ECoG_CNNs/graph.py", line 23, in plot_loss_acc
    plt.plot(range(EPOCH), train_loss_value)
  File "/home/megu/.pyenv/versions/3.7.9/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2842, in plot
    **({"data": data} if data is not None else {}), **kwargs)
  File "/home/megu/.pyenv/versions/3.7.9/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/megu/.pyenv/versions/3.7.9/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/megu/.pyenv/versions/3.7.9/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 399, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (4,) and (20,)
start time:  1633943510
end time:  1633946630
run time:  3120
